### PR TITLE
Added more specific errors

### PR DESCRIPTION
**Pull request by wingedfox**
Added error causes chaining where appropriate
Added error throw for node_modules resolver
Updated tests to reflect changes

### CODE REVIEW

**Comment by wingedfox** [comment]
There are 2 tests failing the same way as they do in master

**Comment by wingedfox** [comment]
@jaredhanson, ping?

**Comment by wingedfox** [comment]
@jaredhanson, should I close this PR?

**Comment by jaredhanson** [comment]
No. I haven't had a chance to review yet

**Comment by wingedfox** [comment]
Have you had a chance to review this PR?

**Comment by wingedfox** [comment]
ping?

**Comment by wingedfox** [comment]
any news?

**Comment by wingedfox** [comment]
ping?

**Comment by jaredhanson** [comment]
Can you describe your use case, in which more specific error classes need to be trapped outside of electrolyte itself?

**Comment by jaredhanson** [comment]
Also, I'd prefer not to take a dependency on `super-error`.  Eventually, I want to port electrolyte to browser-based environments, and I want minimal dependencies in this module.

**Comment by wingedfox** [comment]
> Can you describe your use case, in which more specific error classes need to be trapped outside of electrolyte itself?
- I need to track down errors raised during the module initialization. E.g. 'config' module dies if config file is broken, but existing emplementaton silently skip the errors.
- I need to connect to the database before dependency resolution and provide bootstrap error with the meaningful cause.

Also, I'd like to extend container to make it chainable and there's definitely a need to distinguish the errors inside electrolyte code.

> Also, I'd prefer not to take a dependency on super-error. Eventually, I want to port electrolyte to browser-based environments, and I want minimal dependencies in this module.

Another implementation of extensible errors is welcome, plain old Error is no help in modern applications.

**Comment by jaredhanson** [comment]
Thanks, I see the use case for more specific errors.

> Also, I'd like to extend container to make it chainable and there's definitely a need to distinguish the errors inside electrolyte code.

Could you expand a bit on how you envision this working?

**Comment by jaredhanson** [comment]
I've merged #64, which is equivalent to this PR, but does not take a dependency on super-error.

I'm in the process of evaluating error handling outside of electrolyte, and may make slight adjustments to the actual errors and codes.  I'll update here with my rationale for any changes.  Let me know if you have thoughts or comments.  Thanks!

**Comment by wingedfox** [comment]
Ok.

As of now, electrolyte provides single IoC container used to register dependencies and provides a layer of loaders used to resolve components. This is a core layer of a IoC provider which defines Root Container, used to register common dependencies.

Next, application may utilize layered design for
1. library/subsystem component provisioning
2. runtime provisioning

(1) is useful for unit testing, isolating implementation-related dependencies (e.g. provisioning of a message encoder for mq and http)
(2) is for runtime dependencies provisioning, e.g. request body, requestId, user session and so on

Below I'll describe the latter case.
Most of time we create static, transport- and server-aware controllers implemented with signature `ctrl (req :Request, resp :Response, next :Function)`. This is the easy way to do the things, but on the other hand this prevents us to change underneath implementation because controller begins to knew too much about the infrastructure it is running on.
As long as we already aware of IoC paradigm, it's easy to take next step and make server itself pluggable component, wrapped with tiny layer of code separating business logic (controller) from infrastructure (network transport, application server, etc).
From this point of view container chaining and runtime container provisioning is the 'must have' part of IoC framework, whose main purpose is abstraction business logic from infrastructure and runtime.

```
Root    | application |     winston                                express
        |             |        ^                                      ^
        |             |        :                                      :
Tier 1  | common      |      logger                               app-server
        |             |        ^                                      ^
        |             |        :                                      :
Tier 2  | module      |    child-logger(&logger) <-- controller       : 
        |             |                               :      :        :
        |             |                               v      v        :
Runtime | request     |                          message    requestId :
        |             |                             :           :     :
                                                    -------------------
```
Here is shown as little as possible number of components in order to define concepts, but not to overwhelm the diagram.
*Root* - static root container, provides common space for low-level components, like node_modules, configs and so on.
*Tier 1* - static sub-container which provides implementation-agnostic API, library components (logger) and unification layer for lower-level components (like specific logger initialization code).
*Tier 2* - static sub-container residing business logic related components, like logger with pre-defined message labels, specific controllers and so on.
*Runtime* - dynamic container created to register runtime dependencies like payload, request id, instantiate specific controllers. This containers' lifespan covers single request and is getting disposed on process end.

Instance lookup and registration
All containers are arranged in a tree with common root and directional links from leafs toward the root.
Component lookup is performed starting from the container current component is being registered at.
Component instance is getting registered on the topmost container which full-fills required dependencies.

**Comment by wingedfox** [comment]
> I'm in the process of evaluating error handling outside of electrolyte, and may make slight adjustments to the actual errors and codes. I'll update here with my rationale for any changes. Let me know if you have thoughts or comments. 

I'll try to check new error soon, the only open question for me here is the error serialization in logs, Error does not provide toJSON method and has no enumerable properties which leads to `{}` in JSON logs (e.g. winston logstash serialization).

**Comment by wingedfox** [comment]
@jaredhanson any thoughts?

**Comment by jaredhanson** [comment]
> I'll try to check new error soon, the only open question for me here is the error serialization in logs, Error does not provide toJSON method and has no enumerable properties which leads to {} in JSON logs (e.g. winston logstash serialization).

Given that this is true of Node core itself, and the vast majority of modules in the Node/JavaScript ecosystem, I consider that a problem to be solved at the application layer, rather than any individual module (including electrolyte).  How do you deal with this issue with respect to other modules?

**Comment by jaredhanson** [comment]
I am interested in the idea of layered containers.  Could we drill down into more detail about what would be required to do that, and how the application would use and manage such layered containers?

For instance, for the request/runtime layer, is a separate container used per request, that might have different implementations (for example, based on the `Host` header)?

I'm exploring related ideas with [Bixby.js](https://github.com/bixbyjs), which takes a more interface-oriented approach to injecting dependencies.  At this point, I haven't needed to layer containers, but I'm curious as to how the approach can be enhanced.

**Pull request merged**
